# Generated by Django 4.1.7 on 2023-02-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TweetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "tweet", "ordering": ["-dateCreated"],},
        ),
    ]
