# Generated by Django 4.1.7 on 2023-02-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmodel",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
